DROP TABLE IF EXISTS users;  -- usunięcie tabeli
CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT UNIQUE NOT NULL,
    haslo TEXT NOT NULL
);

DROP TABLE IF EXISTS zadania;  -- usunięcie tabeli
CREATE TABLE zadania (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    id_user INTEGER NOT NULL,
    zadanie TEXT NOT NULL,
    zrobione BOOLEAN NOT NULL DEFAULT 0,
    data_pub TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_user) REFERENCES users(id)
);
